default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: RubyUA
  login: sonin
  password: 15081986


#test:
#  <<: *default
#  database: db/test.sqlite3

production:
  <<: *default
  database: myapp
  pool: 5
  timeout: 5000
  host: 185.65.244.39
  username: sonin
  password: 15081986
